#!/bin/bash

if [ $UID -ne 0 ]
then
  exec sudo $0 "$@"
fi

CLI_VERSION="0.4"

STAR_DIR="/etc/star"
ARRAY_VERSION=$(cat $STAR_DIR/version)

AVAILABLE_COMMAND=()
AVAILABLE_COMMAND+=("starcreatelun lun_name lun_size")
AVAILABLE_COMMAND+=("stardeletelun lun_name [-nop]   # Specify '-nop', does not ask yes/no.")
AVAILABLE_COMMAND+=("starcreatehost host_name host_iqn [lun_name1,lun_name2 ...]")
AVAILABLE_COMMAND+=("stardeletehost host_name [-nop]")
AVAILABLE_COMMAND+=("starattachlun host_name lun_name1[,lun_name2 ...]")
AVAILABLE_COMMAND+=("stardetachlun host_name lun_name1[,lun_name2 ...] [-nop]")
AVAILABLE_COMMAND+=("starlistlun")
AVAILABLE_COMMAND+=("starlisthost")
AVAILABLE_COMMAND+=("starshowpool")
AVAILABLE_COMMAND+=("shootingstar       # Run 'pcs resource move' command.")
AVAILABLE_COMMAND+=("stargazing         # Run 'pcs status' command.")
AVAILABLE_COMMAND+=("starupdatetarget   # Update iSCSI target according to definitions.")
AVAILABLE_COMMAND+=("stargetactive      # Return active controller name.")
AVAILABLE_COMMAND+=("starshowconfig")
AVAILABLE_COMMAND+=("starsetconfig variable1=value1[,variable2=value2 ...]")

POOL_NAME=${POOL_NAME:-STARpool}

NODE_NAME=$(uname -n)
NODE_BASENAME=${NODE_NAME/%?/}
NODE_NUM=${NODE_NAME: -1}
PARTNER_NODE="${NODE_BASENAME}$(( 3 - $NODE_NUM ))"

is_active_node()
{
  pcs resource status STARpool | egrep -q "Started +$(uname -n)"
}

check_active_node()
{
  is_active_node && return 0

  echo "This command must be run on active controller."
  exit 1
}

check_all_nodes_online()
{
  pcs status nodes | grep 'Online:' | grep $NODE_NAME | grep -q $PARTNER_NODE \
      && return 0

  echo "There are offline nodes."
  exit 1
}

targetcli_ls()
{
  CACHE=0

  if [ x"$1" == x"-c" ]
  then
    CACHE=1
    shift
  fi

  CACHE_FILE="$WORKDIR/$(echo $* | sed 's|/|%|g' | sed 's/ /_/g')"

  if [ $CACHE -eq 1 ]
  then
    test -f $CACHE_FILE && { cat $CACHE_FILE ; return ; }
  fi

  targetcli ls $@ | tee $CACHE_FILE
}

starcli()
{
  echo "starcli version $CLI_VERSION"
  echo
  echo 'Available Commands:'

  (
    cd /usr/bin
    for I in $(seq 0 $(( ${#AVAILABLE_COMMAND[@]} - 1 )))
    do
      LINK_NAME=${AVAILABLE_COMMAND[$I]%% *}
      test -L $LINK_NAME || ln -s starcli $LINK_NAME

      echo "  ${AVAILABLE_COMMAND[$I]}"
    done
  )
}

starcreatelun()
{
  LUN_NAME=$1
  LUN_SIZE=$2

  check_active_node
  check_all_nodes_online

  grep -qw "$LUN_NAME" $STAR_DIR/lunlist \
      && { echo "$LUN_NAME is already exists." ; exit 1 ; }

  echo "$LUN_NAME" | grep -qE '^LUN[0-9]+$' \
      || { echo "lun_name must be match pettern '^LUN[0-9]+'." ; exit 1 ; }
  
  echo "$LUN_SIZE" | grep -qE '^[0-9]+M$' \
      || { echo "lun_size must be in megabytes, like '1024M'." ; exit 1 ; }

  LUN_WWN=$(uuidgen)

  lvcreate -n $LUN_NAME -L $LUN_SIZE $POOL_NAME \
      || { echo "Failed to create ${LUN_NAME}." ; exit 1 ; }

  echo "$LUN_NAME $LUN_WWN $LUN_SIZE" >> $STAR_DIR/lunlist

  scp $STAR_DIR/lunlist ${PARTNER_NODE}:${STAR_DIR}

  echo "$LUN_NAME $LUN_WWN $LUN_SIZE"
}

stardeletelun()
{
  LUN_NAME=$1
  NOP=$2

  if [ "x-nop" = "x$NOP" ]
  then
    OPT="-y"
  fi

  check_active_node
  check_all_nodes_online

  grep -qw "$LUN_NAME" $STAR_DIR/lunlist \
      || { echo "$LUN_NAME is not exists." ; exit 1 ; }

  grep -qw "$LUN_NAME" $STAR_DIR/hostlist \
      && { echo "Cannot delete $LUN_NAME, the lun belongs to hosts." ; exit 1 ; }

  NUM_LVS=$(lvs --noheadings | wc -l)
  if [ $NUM_LVS -eq 1 ]
  then
    echo "Cannot delete $LUN_NAME, there must be at least 1 existing LV."
    exit 1
  fi

  lvremove $OPT /dev/$POOL_NAME/$LUN_NAME \
      || { echo "Failed to delete ${LUN_NAME}." ; exit 1 ; }

  grep -vw "$LUN_NAME" $STAR_DIR/lunlist > $STAR_DIR/lunlist.$$
  mv $STAR_DIR/lunlist.$$ $STAR_DIR/lunlist

  scp $STAR_DIR/lunlist ${PARTNER_NODE}:${STAR_DIR}

  echo "$LUN_NAME deleted."
}

version() { echo "$@" | awk -F. '{ printf("%03d%03d%03d\n",$1,$2,$3); }' ; }

create_tgt_port_grp()
{
  if [ $(version "$ARRAY_VERSION") -ge $(version "0.4") ]
  then
    targetcli ls /backstores/block/STAR-${LUN_NAME}/alua \
        | grep -q 'node._tg_pt_gp' \
            || targetcli /backstores/block/STAR-${LUN_NAME}/alua create \
                node${NODE_NUM}_tg_pt_gp ${NODE_NUM}
  fi
}

set_alua_tgt_port_grp()
{
  if [ $(version "$ARRAY_VERSION") -ge $(version "0.4") ]
  then
    targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/luns | grep -w STAR-${LUN_NAME} \
        | grep -q 'node._tg_pt_gp' || {
          lunN=$(targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/luns \
              | awk "/STAR-${LUN_NAME}/{ print \$2 }")
          targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/luns/$lunN \
              set alua alua_tg_pt_gp_name=node${NODE_NUM}_tg_pt_gp ; }
  fi
}

starupdatetarget()
{
  WORKDIR=$(mktemp -d --tmpdir ${COMMAND_NAME}.XXXXXX)

  ##
  ## add objects
  ##
  OLD_IFS=$IFS
  IFS=$'\n'
  for LUN_INFO in $(cat $STAR_DIR/lunlist)
  do
    LUN_NAME=$(echo $LUN_INFO | awk '{ print $1 }')
    LUN_WWN=$(echo $LUN_INFO | awk '{ print $2 }')

    targetcli_ls -c /backstores/block 1 | grep -wq STAR-${LUN_NAME} \
        && { create_tgt_port_grp ; continue ; }

    if is_active_node
    then
      DEV="/dev/STARpool/$LUN_NAME"
    else
      DEV="/dev/disk/by-id/scsi-SLIO-ORG_STAR-${LUN_NAME}_${LUN_WWN}"
      DEV_WITHOUT_WWN="/dev/disk/by-id/scsi-SLIO-ORG_STAR-${LUN_NAME}"

      for OLD_DEV in $(ls -1d ${DEV_WITHOUT_WWN}_* 2> /dev/null | grep -Fv ${DEV})
      do
        echo 1 > /sys/block/$(basename $(readlink $OLD_DEV))/device/delete
      done

      for I in $(seq 1 5)
      do
	ls -1d ${DEV_WITHOUT_WWN}_* 2> /dev/null | grep -Fv ${DEV} \
            && { sleep 1 ; continue ; }
	break
      done

      iscsiadm -m discovery -t sendtargets -p $PARTNER_NODE
      iscsiadm -m node --login

      for SCSI_HOST in $(ls -1d /sys/class/scsi_host/host*)
      do
        echo '- - -' > $SCSI_HOST/scan
      done

      for I in $(seq 1 5)
      do
        test -L ${DEV} || { sleep 1 ; continue ; }
	break
      done
    fi

    targetcli /backstores/block create name=STAR-${LUN_NAME} \
        dev=${DEV} wwn=${LUN_WWN} && create_tgt_port_grp
  done
  IFS=$OLD_IFS

  ARRAY_NAME=$(cat $STAR_DIR/starname)
  ARRAY_TGT_IQN="iqn.2023-09.test.use.only:${ARRAY_NAME}-target"

  targetcli ls /iscsi/$ARRAY_TGT_IQN > /dev/null 2>&1 \
      || targetcli /iscsi create $ARRAY_TGT_IQN

  ARRAY_INIT_IQN="iqn.2023-09.test.use.only:${ARRAY_NAME}-initiator"

  targetcli ls /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$ARRAY_INIT_IQN > /dev/null 2>&1 \
      || targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/acls create $ARRAY_INIT_IQN

  OLD_IFS=$IFS
  IFS=$'\n'
  for LUN_INFO in $(cat $STAR_DIR/lunlist)
  do
    LUN_NAME=$(echo $LUN_INFO | awk '{ print $1 }')

    grep -qw $LUN_NAME $STAR_DIR/hostlist || continue

    targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/luns | grep -qw $LUN_NAME \
        && { set_alua_tgt_port_grp ; continue ; }

    for I in $(seq 0 127)
    do
      targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/luns | grep -wq lun${I} \
          || break
    done

    targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/luns create /backstores/block/STAR-${LUN_NAME} $I false
    targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$ARRAY_INIT_IQN create $I \
        /backstores/block/STAR-${LUN_NAME}
    targetcli_ls /iscsi/$ARRAY_TGT_IQN/tpg1/luns > /dev/null 2>&1

    set_alua_tgt_port_grp
  done

  for HOST_INFO in $(cat $STAR_DIR/hostlist)
  do
    HOST_IQN=$(echo $HOST_INFO | awk '{ print $2 }')
    HOST_LUNS=$(echo $HOST_INFO | awk '{ print $3 }')

    targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls | grep -qw $HOST_IQN \
        || targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/acls create $HOST_IQN false

    for LUN_NAME in $(echo $HOST_LUNS | sed 's/,/\n/g')
    do
      targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$HOST_IQN | grep -qw $LUN_NAME \
          && continue

      for I in $(seq 0 127)
      do
        targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$HOST_IQN | grep -qw mapped_lun${I} \
            || break
      done

      targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$HOST_IQN create $I \
          /backstores/block/STAR-${LUN_NAME}

      targetcli_ls /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$HOST_IQN > /dev/null 2>&1
    done
  done
  IFS=$OLD_IFS

  ##
  ## remove objects
  ##
  for HOST_IQN in \
      $(targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls 1 | grep -v -e acls -e $ARRAY_INIT_IQN | awk '{ print $2 }')
  do
    grep -q "[[:blank:]]${HOST_IQN}[[:blank:]]" $STAR_DIR/hostlist \
        || { targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/acls delete $HOST_IQN ; continue ; }

    for LUN_NAME in $(targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$HOST_IQN \
        | grep mapped_lun | awk -F- '{ print $3 }' | awk '{ print $1 }')
    do
      INDEX=$(targetcli_ls -c /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$HOST_IQN \
          | grep $LUN_NAME | awk '{ print $2 }' | sed 's/mapped_lun//g')

      grep "[[:blank:]]${HOST_IQN}[[:blank:]]" $STAR_DIR/hostlist | grep -qw $LUN_NAME \
          || targetcli /iscsi/$ARRAY_TGT_IQN/tpg1/acls/$HOST_IQN delete $INDEX
    done
  done

  for LUN_NAME in $(targetcli ls /backstores/block | grep STAR- | awk '{ print $2 }' \
      | awk -F- '{ print $2 }')
  do
    grep -wq $LUN_NAME $STAR_DIR/hostlist \
        || targetcli /backstores/block delete STAR-$LUN_NAME
  done

  ##
  ## save and send config to partner node
  ##
  targetcli saveconfig

  RUNNING_CONFIG="/etc/target/saveconfig.json"

  if is_active_node
  then
    STARTUP_CONFIG="${RUNNING_CONFIG}.active"
  else
    STARTUP_CONFIG="${RUNNING_CONFIG}.standby"
  fi

  cp -p $RUNNING_CONFIG $STARTUP_CONFIG

  scp $STARTUP_CONFIG ${PARTNER_NODE}:/etc/target

  rm -rf $WORKDIR
}

starcreatehost()
{
  HOST_NAME=$1
  HOST_IQN=$2
  HOST_LUNS=$3

  check_active_node
  check_all_nodes_online

  grep -qw "$HOST_NAME" $STAR_DIR/hostlist \
      && { echo "$HOST_NAME is already exists." ; exit 1 ; }  

  grep -qw "$HOST_IQN" $STAR_DIR/hostlist \
      && { echo "$HOST_IQN is already exists." ; exit 1 ; }  

  echo "$HOST_NAME $HOST_IQN $HOST_LUNS" >> $STAR_DIR/hostlist

  starupdatetarget

  scp $STAR_DIR/hostlist ${PARTNER_NODE}:$STAR_DIR
  ssh -n -o ConnectTimeout=10 $PARTNER_NODE "/usr/bin/starupdatetarget"

  echo "$HOST_NAME created."  
}

stardeletehost()
{
  HOST_NAME=$1
  NOP=$2

  check_active_node
  check_all_nodes_online

  grep -qw "$HOST_NAME" $STAR_DIR/hostlist \
      || { echo "$HOST_NAME is not exists." ; exit 1 ; }

  if [ "x-nop" = "x$NOP" ]
  then
    :
  else
    echo -n "Delete host ${HOST_NAME}? [y/N]:"
    read YN
    
    case $YN in
      [yY]*)
        :
        ;;
      *)
        echo 'Operation canceled.'
        exit 1
        ;;
    esac
  fi

  grep -vw "$HOST_NAME" $STAR_DIR/hostlist > $STAR_DIR/hostlist.$$
  mv $STAR_DIR/hostlist.$$ $STAR_DIR/hostlist

  starupdatetarget

  scp $STAR_DIR/hostlist ${PARTNER_NODE}:${STAR_DIR}
  ssh -n -o ConnectTimeout=10 $PARTNER_NODE "/usr/bin/starupdatetarget"

  echo "$HOST_NAME deleted."
}

starattachlun()
{
  HOST_NAME=$1
  ATTACH_LUNS=$2

  check_active_node
  check_all_nodes_online

  grep -qw "$HOST_NAME" $STAR_DIR/hostlist \
      || { echo "$HOST_NAME is not exists." ; exit 1 ; }

  for LUN_NAME in $(echo $ATTACH_LUNS | sed 's/,/\n/g')
  do
    grep -w "$HOST_NAME" $STAR_DIR/hostlist | grep -qw $LUN_NAME \
        && { echo "$LUN_NAME is already belongs to ${HOST_NAME}." ; exit 1 ; }
  done

  HOST_INFO=$(grep -w $HOST_NAME $STAR_DIR/hostlist)
  HOST_IQN=$(echo $HOST_INFO | awk '{ print $2 }')
  HOST_LUNS=$(echo $HOST_INFO | awk '{ print $3 }')

  if [ -z "$HOST_LUNS" ]
  then
    HOST_LUNS="$ATTACH_LUNS"
  else
    HOST_LUNS=$(echo "${HOST_LUNS},${ATTACH_LUNS}" \
        | sed 's/,/\n/g' | sort | tr '\n' ',' | sed 's/,$/\n/g')
  fi

  cat $STAR_DIR/hostlist \
      | sed 's/'"${HOST_NAME}"' .*/'"${HOST_NAME} ${HOST_IQN} ${HOST_LUNS}"'/g' \
          > $STAR_DIR/hostlist.$$
  mv $STAR_DIR/hostlist.$$ $STAR_DIR/hostlist

  starupdatetarget

  scp $STAR_DIR/hostlist ${PARTNER_NODE}:${STAR_DIR}
  ssh -n -o ConnectTimeout=10 $PARTNER_NODE "/usr/bin/starupdatetarget"

  echo "${ATTACH_LUNS} atached to ${HOST_NAME}." 
}

stardetachlun()
{
  HOST_NAME=$1
  DETACH_LUNS=$2
  NOP=$3

  check_active_node
  check_all_nodes_online

  grep -qw "$HOST_NAME" $STAR_DIR/hostlist \
      || { echo "$HOST_NAME is not exists." ; exit 1 ; }

  for LUN_NAME in $(echo $DETACH_LUNS | sed 's/,/\n/g')
  do
    grep -w "$HOST_NAME" $STAR_DIR/hostlist | grep -qw $LUN_NAME \
        || { echo "$LUN_NAME is not belongs to ${HOST_NAME}." ; exit 1 ; }
  done

  if [ "x-nop" = "x$NOP" ]
  then
    :
  else
    echo -n "Detach ${DETACH_LUNS} from ${HOST_NAME}? [y/N]:"
    read YN

    case $YN in
      [yY]*)
        :
        ;;
      *)
        echo 'Operation canceled.'
        exit 1
        ;;
    esac
  fi

  HOST_INFO=$(grep -w $HOST_NAME $STAR_DIR/hostlist)
  HOST_IQN=$(echo $HOST_INFO | awk '{ print $2 }')
  HOST_LUNS=$(echo $HOST_INFO | awk '{ print $3 }')

  for LUN_NAME in $(echo $DETACH_LUNS | sed 's/,/\n/g')
  do
    HOST_LUNS=$(echo "${HOST_LUNS}" | sed 's/,/\n/g' | grep -vw $LUN_NAME \
        | sort | tr '\n' ',' | sed 's/,$/\n/g')
  done

  cat $STAR_DIR/hostlist \
      | sed 's/'"${HOST_NAME}"' .*/'"${HOST_NAME} ${HOST_IQN} ${HOST_LUNS}"'/g' \
          > $STAR_DIR/hostlist.$$
  mv $STAR_DIR/hostlist.$$ $STAR_DIR/hostlist

  starupdatetarget

  scp $STAR_DIR/hostlist ${PARTNER_NODE}:${STAR_DIR}
  ssh -n -o ConnectTimeout=10 $PARTNER_NODE "/usr/bin/starupdatetarget"

  echo "$DETACH_LUNS detached from ${HOST_NAME}."
}

stargetactive()
{
  if is_active_node
  then
    echo $NODE_NAME
  else
    echo $PARTNER_NODE
  fi
}

starsetconfig()
{
  VAR_VAL_LIST=$1

  check_active_node
  check_all_nodes_online

  for VAR_VAL in $(echo $VAR_VAL_LIST | sed 's/,/\n/g')
  do
    VAR=${VAR_VAL%=*}
    grep -wq "$VAR" $STAR_DIR/config \
        || { echo "Invalid variable $VAR skipped." ; continue ; }
    echo "$VAR_VAL"
    sed -i "s/^${VAR}=.*/$VAR_VAL/g" $STAR_DIR/config
  done

  scp $STAR_DIR/config ${PARTNER_NODE}:${STAR_DIR}

  echo 'For apply in most cases, need to failover with `shootingstar` command.'
}

COMMAND_NAME=$(basename $0)

case $COMMAND_NAME in
  starlistlun)
    cat $STAR_DIR/lunlist
    ;;
  starlisthost)
    cat $STAR_DIR/hostlist
    ;;
  starshowpool)
    check_active_node
    vgdisplay
    ;;
  shootingstar)
    check_active_node
    check_all_nodes_online
    pcs resource move STARpool --autodelete
    ;;
  stargazing)
    pcs status
    ;;
  starshowconfig)
    cat $STAR_DIR/config
    ;;
  *)
    $COMMAND_NAME "$@"
    ;;
esac
